//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosaic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mosaic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackItem {
            get {
                return ResourceManager.GetString("BackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Mosaic.
        /// </summary>
        public static string ExitItem {
            get {
                return ResourceManager.GetString("ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Mosaic.
        /// </summary>
        public static string OptionsAbout {
            get {
                return ResourceManager.GetString("OptionsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosaic uses Awesomium web-browser framework. Awesomium is a trademark of Khrona LLC © 2011 Khrona LLC.
        /// </summary>
        public static string OptionsAboutAwesomium {
            get {
                return ResourceManager.GetString("OptionsAboutAwesomium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some icons provided by The Noun Project..
        /// </summary>
        public static string OptionsAboutIcons {
            get {
                return ResourceManager.GetString("OptionsAboutIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string OptionsAboutTabHeader {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string OptionsApplyButton {
            get {
                return ResourceManager.GetString("OptionsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        public static string OptionsBg {
            get {
                return ResourceManager.GetString("OptionsBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string OptionsCancelButton {
            get {
                return ResourceManager.GetString("OptionsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string OptionsChangeBg {
            get {
                return ResourceManager.GetString("OptionsChangeBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is protected by copyright law and distributed under Microsoft Public License..
        /// </summary>
        public static string OptionsCopyright {
            get {
                return ResourceManager.GetString("OptionsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable widget animation.
        /// </summary>
        public static string OptionsEnableAnimation {
            get {
                return ResourceManager.GetString("OptionsEnableAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable windows thumbnails bar.
        /// </summary>
        public static string OptionsEnableThumbBar {
            get {
                return ResourceManager.GetString("OptionsEnableThumbBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable fullscreen mode.
        /// </summary>
        public static string OptionsExclusiveMode {
            get {
                return ResourceManager.GetString("OptionsExclusiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string OptionsGeneralTabHeader {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string OptionsItem {
            get {
                return ResourceManager.GetString("OptionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OptionsOkButton {
            get {
                return ResourceManager.GetString("OptionsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be applied after restarting Mosaic..
        /// </summary>
        public static string OptionsRestart {
            get {
                return ResourceManager.GetString("OptionsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        public static string OptionsUI {
            get {
                return ResourceManager.GetString("OptionsUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion {
            get {
                return ResourceManager.GetString("OptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mosaic options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select friends that you want to pin on a start screen.
        /// </summary>
        public static string PeopleHubTip {
            get {
                return ResourceManager.GetString("PeopleHubTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends....
        /// </summary>
        public static string PeopleItem {
            get {
                return ResourceManager.GetString("PeopleItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin application.
        /// </summary>
        public static string PinAppItem {
            get {
                return ResourceManager.GetString("PinAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin website.
        /// </summary>
        public static string PinWebItem {
            get {
                return ResourceManager.GetString("PinWebItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshItem {
            get {
                return ResourceManager.GetString("RefreshItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Config.
        /// </summary>
        public static string SaveItem {
            get {
                return ResourceManager.GetString("SaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartItem {
            get {
                return ResourceManager.GetString("StartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of this widget is visible only in fullscreen mode..
        /// </summary>
        public static string WidgetInvisible {
            get {
                return ResourceManager.GetString("WidgetInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets....
        /// </summary>
        public static string WidgetsItem {
            get {
                return ResourceManager.GetString("WidgetsItem", resourceCulture);
            }
        }
    }
}
