//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Newgen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Newgen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackItem {
            get {
                return ResourceManager.GetString("BackItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string ConnectItem {
            get {
                return ResourceManager.GetString("ConnectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Newgen.
        /// </summary>
        public static string ExitItem {
            get {
                return ResourceManager.GetString("ExitItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string LockItem {
            get {
                return ResourceManager.GetString("LockItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12-hour time.
        /// </summary>
        public static string Options12H {
            get {
                return ResourceManager.GetString("Options12H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 24-hour time.
        /// </summary>
        public static string Options24H {
            get {
                return ResourceManager.GetString("Options24H", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Newgen.
        /// </summary>
        public static string OptionsAbout {
            get {
                return ResourceManager.GetString("OptionsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen uses Awesomium web-browser framework. Awesomium is a trademark of Khrona LLC © 2011 Khrona LLC.
        /// </summary>
        public static string OptionsAboutAwesomium {
            get {
                return ResourceManager.GetString("OptionsAboutAwesomium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some icons provided by The Noun Project..
        /// </summary>
        public static string OptionsAboutIcons {
            get {
                return ResourceManager.GetString("OptionsAboutIcons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string OptionsAboutTabHeader {
            get {
                return ResourceManager.GetString("OptionsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply.
        /// </summary>
        public static string OptionsApplyButton {
            get {
                return ResourceManager.GetString("OptionsApplyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color:.
        /// </summary>
        public static string OptionsBg {
            get {
                return ResourceManager.GetString("OptionsBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color transparency:.
        /// </summary>
        public static string OptionsBgAlpha {
            get {
                return ResourceManager.GetString("OptionsBgAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image:.
        /// </summary>
        public static string OptionsBgImg {
            get {
                return ResourceManager.GetString("OptionsBgImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select image.
        /// </summary>
        public static string OptionsBgImgSelect {
            get {
                return ResourceManager.GetString("OptionsBgImgSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use image in backgound.
        /// </summary>
        public static string OptionsBgImgUse {
            get {
                return ResourceManager.GetString("OptionsBgImgUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string OptionsCancelButton {
            get {
                return ResourceManager.GetString("OptionsCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string OptionsChangeBg {
            get {
                return ResourceManager.GetString("OptionsChangeBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change.
        /// </summary>
        public static string OptionsChangeStaticAppWidgetBgColor {
            get {
                return ResourceManager.GetString("OptionsChangeStaticAppWidgetBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This software is protected by copyright law and distributed under Microsoft Public License..
        /// </summary>
        public static string OptionsCopyright {
            get {
                return ResourceManager.GetString("OptionsCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable widget animation.
        /// </summary>
        public static string OptionsEnableAnimation {
            get {
                return ResourceManager.GetString("OptionsEnableAnimation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Newgen when Windows loads.
        /// </summary>
        public static string OptionsEnableAutoStart {
            get {
                return ResourceManager.GetString("OptionsEnableAutoStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable windows thumbnails bar.
        /// </summary>
        public static string OptionsEnableThumbBar {
            get {
                return ResourceManager.GetString("OptionsEnableThumbBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable touch support.
        /// </summary>
        public static string OptionsEnableTouch {
            get {
                return ResourceManager.GetString("OptionsEnableTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable UserTile (User name and Picture) on main screen..
        /// </summary>
        public static string OptionsEnableUserTile {
            get {
                return ResourceManager.GetString("OptionsEnableUserTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable fullscreen mode.
        /// </summary>
        public static string OptionsExclusiveMode {
            get {
                return ResourceManager.GetString("OptionsExclusiveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string OptionsGeneralTabHeader {
            get {
                return ResourceManager.GetString("OptionsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string OptionsItem {
            get {
                return ResourceManager.GetString("OptionsItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string OptionsLanguage {
            get {
                return ResourceManager.GetString("OptionsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock screen time (in minutes) (use blank for no screen):.
        /// </summary>
        public static string OptionsLockScreenTime {
            get {
                return ResourceManager.GetString("OptionsLockScreenTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OptionsOkButton {
            get {
                return ResourceManager.GetString("OptionsOkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes will be applied after restarting Newgen..
        /// </summary>
        public static string OptionsRestart {
            get {
                return ResourceManager.GetString("OptionsRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom color for pinned applications background.
        /// </summary>
        public static string OptionsStaticAppWidgetBg {
            get {
                return ResourceManager.GetString("OptionsStaticAppWidgetBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom color for Pinned applications background :.
        /// </summary>
        public static string OptionsStaticAppWidgetBgColor {
            get {
                return ResourceManager.GetString("OptionsStaticAppWidgetBgColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiles size:.
        /// </summary>
        public static string OptionsTilesSize {
            get {
                return ResourceManager.GetString("OptionsTilesSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Space between tiles:.
        /// </summary>
        public static string OptionsTilesSpacing {
            get {
                return ResourceManager.GetString("OptionsTilesSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string OptionsTime {
            get {
                return ResourceManager.GetString("OptionsTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time format:.
        /// </summary>
        public static string OptionsTimeFormat {
            get {
                return ResourceManager.GetString("OptionsTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touch Support.
        /// </summary>
        public static string OptionsTouch {
            get {
                return ResourceManager.GetString("OptionsTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        public static string OptionsUI {
            get {
                return ResourceManager.GetString("OptionsUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string OptionsVersion {
            get {
                return ResourceManager.GetString("OptionsVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Newgen options.
        /// </summary>
        public static string OptionsWindowTitle {
            get {
                return ResourceManager.GetString("OptionsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin application.
        /// </summary>
        public static string PinAppItem {
            get {
                return ResourceManager.GetString("PinAppItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin website.
        /// </summary>
        public static string PinWebItem {
            get {
                return ResourceManager.GetString("PinWebItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshItem {
            get {
                return ResourceManager.GetString("RefreshItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveItem {
            get {
                return ResourceManager.GetString("RemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Config.
        /// </summary>
        public static string SaveItem {
            get {
                return ResourceManager.GetString("SaveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search your files and folders ....
        /// </summary>
        public static string SearchHubTip {
            get {
                return ResourceManager.GetString("SearchHubTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchItem {
            get {
                return ResourceManager.GetString("SearchItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select friends that you want to pin on a start screen.
        /// </summary>
        public static string ShareHubTip {
            get {
                return ResourceManager.GetString("ShareHubTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string ShareItem {
            get {
                return ResourceManager.GetString("ShareItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string StartItem {
            get {
                return ResourceManager.GetString("StartItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tiles.
        /// </summary>
        public static string TilesItem {
            get {
                return ResourceManager.GetString("TilesItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what&apos;s new?.
        /// </summary>
        public static string WhatsNew {
            get {
                return ResourceManager.GetString("WhatsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The content of this widget is visible only in fullscreen mode..
        /// </summary>
        public static string WidgetInvisible {
            get {
                return ResourceManager.GetString("WidgetInvisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Widgets.
        /// </summary>
        public static string WidgetsItem {
            get {
                return ResourceManager.GetString("WidgetsItem", resourceCulture);
            }
        }
    }
}
